# Generated by Django 3.1.5 on 2021-01-10 10:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movieplayer',
            unique_together={('user', 'movie')},
        ),
    ]
